### ISSUE TITLE
(Request) GR3.8 back port or similar OOT module 

### ISSUE THREAD

**Issue by alphafox02** [muaddib1984/gr-JAERO#1]
Would it be possible to make a similar OOT module for Gnuradio 3.8? I have lots of SDRs and could test results, just haven’t got around to converting to 3.9. I’d like to include this in DragonOS. 

If not, I’ll test once I’m setup with 3.9 or higher.

**Comment by alphafox02** [comment]
I'm sure there's a lot more to it, but I changed the Cmakelists to allow a build against 3.8, then started plugging in the gaps and making changes, but there's probably way more to be done that I'm just not familiar with. See attachment as built and opened on DragonOS using one of your example flow graphs, I had to change the soapy input etc, but maybe with some work it could be usable in 3.8. 
![screen](https://user-images.githubusercontent.com/44436101/159190288-0b4014bc-6c52-4f31-a0fa-fb814c4840b1.jpg)

**Comment by alphafox02** [comment]
Well, it's no longer red. Now to test. 
![screen2](https://user-images.githubusercontent.com/44436101/159190815-edb8c00c-bbbe-4b0a-bd1f-dadfe174d808.jpg)

**Comment by alphafox02** [comment]
By opening the flow graphs within GR 3.8 and changing the Window Win Hamming to Hamming in all mentioned areas, to include the Heir block, the flow graph opens and runs with an RTLSDR using the 3.8 OOT Soapy Source block and/or osmosdr blocks. I'll have to hook up a proper antenna and turn on the bias t to see if in fact this actually works, but it appears to be as I can see all the spectrum windows minus the top left being populated. (just realized I didn't have the freq sink hooked up, it now has all spectrum windows populated)

**Comment by muaddib1984** [comment]
Wow, so cool that you've got this working with 3.8 and would be great to see it in DragonOS!
As you saw its a pretty simplistic block. It was only needed because of the differences between GNURadio and JAERO's ZMQ interfaces (JAERO needs to see the sample rate with every message so it can know what's coming in).
I added the USB demod for fun and in case folks weren't proficient with GNURadio they could at least get a channel working.
I just hooked up my RTL Patch (literally in the wee hours of the morning), so i've got this running with a V3 dongle right now and it's working on a 1200 channel.
Let me know if it works out.

**Comment by alphafox02** [comment]
![screen6](https://user-images.githubusercontent.com/44436101/159192837-ac01b474-9dd9-4959-bf67-5a1339d2b917.jpg)

**Comment by alphafox02** [comment]
That's with the RSP1A (SDRPlay). I was shocked to see the data coming in! Probably the first and only GNU Radio project I ever "converted" haha..

**Comment by alphafox02** [comment]
Now if I can just figure out the proper way to submit a PR and branch, I'd be more then happy to make more GRC files for other SDRs that have bias t.

**Comment by alphafox02** [comment]
https://github.com/alphafox02/gr-JAERO/tree/dragonos_gr3.8

**Comment by muaddib1984** [comment]
I'm not the expert on pull requests either, but IIRC you just need to do a git checkout -b <branch name> on your fork then on my repo you can click 'submit pull request'.

**Comment by alphafox02** [comment]
I’ll give it a shot today, super cool you put this project together. Also cool that it can run on an older GR version with some minor changes. Now I just need to learn more about Jaero, zmq, etc!

**Comment by alphafox02** [comment]
Thinking instead of another branch, it’d possible for your main branch to offer support for both 3.8 and 3.9+, however you’d have to have two differently named heir blocks and separate sets of flow graphs. For those with 3.8 they most likely at least have osmosdr, so flow graphs could be created for that and include (unless they have the oot gr-soapy). 3.9+ would just use your stock soapy flow graphs. I’ll close this now that I figured out, I think, how to do a PR

**Comment by muaddib1984** [comment]
FYI, I'm gonna be posting a rework of the USB demodulator. I got some more insight into USB for I/Q and the way it's implemented here (while correct) is WAY over complicated. The change will also make it more scalable to do multi-channel/multi-instance which baldgeek had expressed interest in. Keep an eye out.

**Comment by alphafox02** [comment]
Hey sorry I haven’t gotten back to you, check this out if you get a chance https://drive.google.com/drive/folders/1dVY38ble-8-ybqVwXE6iBAHNM176Uyda that’s the image I’m working on now for the pi (has GR3.10 and GR-Jaero). Hoping to test it more tonight. The desktop build is still 3.8.
