### ISSUE TITLE
FindGnuradio.cmake module path not provided

### ISSUE THREAD

**Issue by thebaldgeek** [muaddib1984/gr-JAERO#2]
Fresh Ubuntu 20.04 install.
Following your build outline (please add 'cd build') I get the following error:

:~/gr-jaero/build$ cmake ..
-- Build type not specified: defaulting to release.
CMake Error at CMakeLists.txt:76 (find_package):
  By not providing "FindGnuradio.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Gnuradio",
  but CMake did not find one.

  Could not find a package configuration file provided by "Gnuradio"
  (requested version 3.9) with any of the following names:

    GnuradioConfig.cmake
    gnuradio-config.cmake

  Add the installation prefix of "Gnuradio" to CMAKE_PREFIX_PATH or set
  "Gnuradio_DIR" to a directory containing one of the above files.  If
  "Gnuradio" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!
See also "/home/developer/gr-jaero/build/CMakeFiles/CMakeOutput.log".
See also "/home/developer/gr-jaero/build/CMakeFiles/CMakeError.log".

**Comment by thebaldgeek** [comment]
I'm told by @[alphafox02] that the build instruction you provide will not actually install gnuradio.
Not sure how to proceed at this point, but perhaps this issue is a non-issue?

**Comment by muaddib1984** [comment]
@thebaldgeek so glad you found my repo! I was actually going to reach to you since your recent work with JAERO has been coming along nicely, unfortunately i'm not on twitter so.....

I have fixed the build instructions to add ```cd build``` thank you for pointing this out.
Yes, gr-JAERO does not install GNURadio, actually none of the ```gr-<does something cool>``` will install GNURadio as they are modules to the main program. I have also updated the README to point to the GNURadio wiki for tutorials and installation.

**Comment by thebaldgeek** [comment]
Thanks for your help.
Here is what was required on a clean Ubuntu 20.04 Server install.

sudo apt install build-essential
sudo add-apt-repository ppa:gnuradio/gnuradio-releases-3.9
sudo apt update
sudo apt install gnuradio
sudo apt install doxygen
sudo apt install graphviz
sudo apt install xterm

Then follow your build.

**Comment by muaddib1984** [comment]
nice, thanks for this. on desktop i don't believe doxygen, graphviz or xterm is necessary, but i haven't done a server install yet. If you want to jump on the [GNURadio chat](chat.gnuradio.org) or the [GNURadio email list](https://wiki.gnuradio.org/index.php/MailingLists#The_lists) we can see about updating the docs to include the extra dependencies for a server install. 
Glad this worked out!
