### ISSUE TITLE
How to change center frequency and spread of main range?

### ISSUE THREAD

**Issue by thebaldgeek** [muaddib1984/gr-JAERO#4]
Depending on the band (L or C) and the satellite the user is under, it is necessary to change the starting center frequency?
Out of the box, I am unable to tune to to 1545101000 to get my first 98W L-Band channel.
Is it possible to also change the spread of the main display?
I need to go from 1.542.700.000 to 1.546.100.000 to cover voice to the top 10500 data channel. How can I set that range?

**Comment by muaddib1984** [comment]
that's interesting. i just fired up with my V3 dongle and frequency adjust works fine. are you adjusting the "SDR Center Frequency" slider?
I did notice that on my GUI window, the frequency adjustment was kind of cutoff at the bottom, so i had to scroll down. Not trying to insult your intelligence or anything, but I wrote the flowgraph and it caught me off guard!

**Comment by thebaldgeek** [comment]
Not a problem at all, its a new to me UI, so its good to question everything.    
I can't take a screenshot right now, but moving the frequency adjustment slider does indeed move the range up/down, its just not enough to get to where I need to go on L-Band and for sure not enough for our (there are three of us) C-Band which is what I really want to use this for.

**Comment by muaddib1984** [comment]
The RTL example flowgraph's SDR Center Frequency slider tunes up to 2200MHz, so 1545101000 shouldn't be an issue. Maybe i'm not understanding the question? If it doesn't tune where you want it, you can double click the QT GUI Range widget in the flowgraph just below the Soapy RTLSDR source and change the 'stop' value to whatever you like. 

Also, regarding your first post, i didn't answer your question about the main spread of the display. I'm assuming you mean graphically wider as opposed to more bandwidth?
Yes, after playing around with it a bit more i'm considering a slight rework of the GUI. I can organize them better with tabs, like one tab would have the whole spectrum across the entire window and maybe a waterfall underneath (a-la SDR Sharp/Fosphor) and the other tab would be the existing display and look like it does now. Would that help?

**Comment by muaddib1984** [comment]
Closed due to no response. Feel free to open a new issue if this is still something you want help with.
