### ISSUE TITLE
Sample rate different than expected

### ISSUE THREAD

**Issue by alphafox02** [muaddib1984/gr-JAERO#6]
Setup:
- Latest Gr-Jaero with Gnuradio 3.10.1.1 on aarch64. 
- Soapy and Osmosdr source blocks used with default sample rate.
- Rtlsdr v3
- Jaero v1.0.4.13

Expected behavior:
Start up Jaero and be able to connect to Zmq on port 6001.

Observed behavior:
Flow graph executes and appears to be working, but upon starting Jaero and making connection to port 6001 Jaero will say the following in terminal and exit 

Sample rate different than expected. Trying to change demodulator sample rate terminate called after throwing an instance of ‘std:bad_alloc’ what(): std::bad_alloc
/usr/local/bin/jaero: line 2: Aborted core dumped /opt/jaero/JAERO 

I thought maybe it was something with Jaero, however I checked also using SDRReceiver with the 98 based sample conf file and although jaero says “sample rate different than expected. Trying to change demodulator sample rate” it only makes that comment and continues to run and receive.

**Comment by muaddib1984** [comment]
This is undesired behavior for sure!

Is this on a raspberry pi4? If so, I have one of those and I can test it out. 

I’m not sure if this will affect things, but in the JAERO settings try checking “enable wideband ……” If it’s not already. 

Also make sure that the rate field in gr-JAERO is set to 48000. 

I will look at this as well as push the new, simpler USB Demod in the next few days. 

<end transmission>

**Comment by alphafox02** [comment]
Quickly checked both settings and enabled the one in jaero, but same result. It very well could be something unique to gif image I’m building for the Pi4. I’ll be curious to see if it works for you, but if you’d like to try on my image it’s here https://drive.google.com/drive/folders/1dVY38ble-8-ybqVwXE6iBAHNM176Uyda

you’ll have to create the .grc_gnuradio in the home directory and copy the heir block stuff to it once created. Username is Ubuntu and password is dragon. Needs a 32Gb sd card.

**Comment by muaddib1984** [comment]
FYI, GNURadio 3.10.2.0 fixes the .grc_gnuradio directory issue. It is now created when you generate a hier block for the first time or new hier blocks are just added to .grc_gnuradio

**Comment by muaddib1984** [comment]
@alphafox02 i haven't forgotten about you. i tried to setup my pi4 last night, but i think the image has to be fully expanded? I didn't have 32GB extra space on my machine to decompress, so i'll try it on a different one tonight.
i'm thinking this is a zmq issue or a python issue with byte sizes. I'll test it out.

**Comment by alphafox02** [comment]
No rush. I’m keeping an eye out for the ppa build of 3.10.2. For the image I linked above, you should be able to burn it compressed as is to a 32gb card with etcher or the pi image tool and I’ll format it correct. On first boot it’ll expand to the full size of your sd card, but perhaps I should check the image I uploaded again.

**Comment by muaddib1984** [comment]
@alphafox02 Thank you so much for finding this bug. It's fixed now! Tested on my DragonOS RPI4 as well as my x86 test machine. Bugfix is merged into main. 
Let me know once you test it and make sure it's all up to your liking.

I'm still not 100% sure why this was working on x86 and not aarch64, but given that this is a sum of many parts there's a lot of places to point (including that i just got lucky with the first implementation).
Anyways, enjoy. I updated the README, C-Band 10500 burst and L-Band 8400 voice is confirmed working!

**Comment by alphafox02** [comment]
Excellent! I’ll build it today, update the image and close out the ticket. I’m trying to go one by one and make sure each GR 3.10 oot module works. Can’t wait to see how the voice part works, I guess I didn’t realize there’s audio?

**Comment by muaddib1984** [comment]
Yea, JAERO has an audio channel decoder. That’s the libaeroambe message at the beginning. 

<end transmission>

**Comment by alphafox02** [comment]
Built and received message on my Pi4!
